version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    # Baseline "industry standard" Go checks.
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - unused
    - misspell
    - unparam
    - errorlint

  settings:
    misspell:
      # Words used intentionally in CLI context.
      ignore-rules:
        - cancelled
        - cancelling
